<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import axios from 'axios';

const user = ref(null);
const loading = ref(false);
const error = ref('');
const active = ref('dashboard');
const mobileNavOpen = ref(false);
const dashboard = ref({ metrics: {}, employees: [], periods: [], recent_audit: [], tenant: null });
const employees = ref({ data: [] });
const organization = ref({ branches: [], departments: [], designations: [], grades: [], employment_types: [] });
const leave = ref({ types: [], balances: [], requests: [] });
const payroll = ref({ periods: [], transactions: [] });
const login = reactive({ email: '', password: '', remember: false });
const employeeForm = reactive({ employee_no: '', first_name: '', middle_name: '', last_name: '', email: '', phone: '', employment_status: 'Active', basic_salary: 0, branch_id: null, department_id: null });
const leaveForm = reactive({ employee_id: null, leave_type_id: null, start_date: '', end_date: '', days_requested: 1, reason: '' });

const navItems = [
    { key: 'dashboard', label: 'Overview', icon: 'bi-grid-1x2-fill', description: 'Workspace snapshot' },
    { key: 'employees', label: 'Employees', icon: 'bi-people-fill', description: 'People directory' },
    { key: 'organization', label: 'Organization', icon: 'bi-diagram-3-fill', description: 'Teams and branches' },
    { key: 'leave', label: 'Leave', icon: 'bi-calendar2-check-fill', description: 'Requests and balances' },
    { key: 'payroll', label: 'Payroll', icon: 'bi-wallet2', description: 'Pay runs and reports' },
    { key: 'ess', label: 'My ESS', icon: 'bi-person-badge-fill', description: 'Your employee profile' },
    { key: 'audit', label: 'Audit trail', icon: 'bi-shield-check', description: 'Activity history' },
];

const pageMeta = computed(() => {
    const page = navItems.find((item) => item.key === active.value);
    return page || navItems[0];
});
const role = computed(() => user.value?.role?.value || user.value?.role || 'Employee');
const isEmployee = computed(() => role.value === 'Employee');
const canManagePeople = computed(() => ['Super Admin', 'Company Admin', 'HR Manager'].includes(role.value));
const canProcessPayroll = computed(() => ['Super Admin', 'Company Admin', 'Payroll Manager'].includes(role.value));
const initials = computed(() => (user.value?.name || 'HR').split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase());
const money = (value) => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(Number(value || 0));
const fullName = (row) => row?.full_name || [row?.first_name, row?.middle_name, row?.last_name].filter(Boolean).join(' ');
const statusClass = (status) => ({ Approved: 'status-approved', Rejected: 'status-rejected', Pending: 'status-pending', Active: 'status-approved' }[status] || 'status-neutral');

async function apiGet(url, params = {}) { const response = await axios.get(url, { params }); return response.data; }
async function loadAll() { loading.value = true; error.value = ''; try { dashboard.value = await apiGet('/api/dashboard'); employees.value = await apiGet('/api/employees'); organization.value = await apiGet('/api/organization'); leave.value = await apiGet('/api/leave'); payroll.value = await apiGet('/api/payroll'); } catch (e) { error.value = e.response?.data?.message || 'Unable to load HR data.'; } finally { loading.value = false; } }
async function signIn() { loading.value = true; error.value = ''; try { await axios.get('/sanctum/csrf-cookie'); const response = await axios.post('/api/auth/login', login); user.value = response.data.user; await loadAll(); } catch (e) { error.value = e.response?.data?.message || 'Sign in failed.'; } finally { loading.value = false; } }
async function signOut() { await axios.post('/api/auth/logout'); user.value = null; }
async function createEmployee() { error.value = ''; try { await axios.post('/api/employees', employeeForm); Object.assign(employeeForm, { employee_no: '', first_name: '', middle_name: '', last_name: '', email: '', phone: '', employment_status: 'Active', basic_salary: 0, branch_id: null, department_id: null }); await loadAll(); active.value = 'employees'; } catch (e) { error.value = e.response?.data?.message || 'Could not create employee.'; } }
async function submitLeave() { try { await axios.post('/api/leave/requests', leaveForm); Object.assign(leaveForm, { employee_id: null, leave_type_id: null, start_date: '', end_date: '', days_requested: 1, reason: '' }); await loadAll(); } catch (e) { error.value = e.response?.data?.message || 'Could not submit leave request.'; } }
async function decideLeave(request, status) { try { await axios.post(`/api/leave/requests/${request.id}/decision`, { status, decision_comment: status === 'Approved' ? 'Approved in HR workspace' : 'Decision recorded in HR workspace' }); await loadAll(); } catch (e) { error.value = e.response?.data?.message || 'Could not update leave request.'; } }
async function processPayroll(periodId) { if (!periodId) return; try { await axios.post('/api/payroll/process', { payroll_period_id: periodId }); await loadAll(); active.value = 'payroll'; } catch (e) { error.value = e.response?.data?.message || 'Could not process payroll.'; } }
function downloadEmployees() { window.location.href = '/api/reports/employees.xlsx'; }
function downloadPayslip(transactionId) { window.location.href = `/api/reports/payslips/${transactionId}.pdf`; }
function setActive(section) { active.value = section; mobileNavOpen.value = false; }

onMounted(async () => { try { const response = await apiGet('/api/auth/me'); user.value = response.user; await loadAll(); } catch (_) {} });
</script>

<template>
  <div v-if="!user" class="login-screen">
    <div class="login-glow login-glow-one"></div>
    <div class="login-glow login-glow-two"></div>
    <div class="login-layout">
      <section class="login-intro d-none d-lg-flex">
        <div>
          <div class="brand-lockup brand-lockup-light mb-5"><div class="brand-mark">BP</div><div><div class="brand-name">BluePrint <span>HR</span></div><div class="brand-caption">People operations, simplified</div></div></div>
          <div class="eyebrow eyebrow-light">The modern HR workspace</div>
          <h1>Build a better<br><span>employee experience.</span></h1>
          <p>One calm, connected place for your people, payroll and everyday HR operations.</p>
        </div>
        <div class="login-feature-list">
          <div><i class="bi bi-check2-circle"></i><span>One source of truth for your workforce</span></div>
          <div><i class="bi bi-check2-circle"></i><span>Payroll-ready workflows with clear audit trails</span></div>
          <div><i class="bi bi-check2-circle"></i><span>Secure by design, effortless to use</span></div>
        </div>
      </section>
      <section class="login-panel">
        <div class="brand-lockup mb-5 d-lg-none"><div class="brand-mark">BP</div><div><div class="brand-name">BluePrint <span>HR</span></div><div class="brand-caption">People operations, simplified</div></div></div>
        <div class="login-heading"><div class="eyebrow">Welcome back</div><h2>Sign in to your workspace</h2><p>Use your organization account to continue.</p></div>
        <div v-if="error" class="alert alert-danger alert-soft d-flex gap-2 align-items-start"><i class="bi bi-exclamation-circle"></i><span>{{ error }}</span></div>
        <form @submit.prevent="signIn" class="login-form">
          <div class="field-group"><label class="form-label" for="login-email">Work email</label><div class="input-with-icon"><i class="bi bi-envelope"></i><input id="login-email" v-model="login.email" type="email" class="form-control" placeholder="you@company.com" required autocomplete="email"></div></div>
          <div class="field-group"><div class="d-flex justify-content-between"><label class="form-label" for="login-password">Password</label><span class="form-hint">Keep your account secure</span></div><div class="input-with-icon"><i class="bi bi-lock"></i><input id="login-password" v-model="login.password" type="password" class="form-control" placeholder="Enter your password" required autocomplete="current-password"></div></div>
          <div class="d-flex align-items-center justify-content-between mb-4"><div class="form-check"><input id="remember" v-model="login.remember" class="form-check-input" type="checkbox"><label class="form-check-label" for="remember">Remember me</label></div><span class="secure-note"><i class="bi bi-shield-lock"></i> Secure sign in</span></div>
          <button class="btn btn-primary btn-lg w-100" :disabled="loading"><span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>{{ loading ? 'Signing in…' : 'Sign in to BluePrint HR' }}<i v-if="!loading" class="bi bi-arrow-right ms-2"></i></button>
        </form>
        <div class="login-footer"><i class="bi bi-info-circle"></i><span>Development seed credentials are documented in the Laravel README. Rotate them before production.</span></div>
      </section>
    </div>
  </div>

  <div v-else class="app-shell">
    <div v-if="mobileNavOpen" class="mobile-nav-backdrop d-lg-none" @click="mobileNavOpen = false"></div>
    <aside class="sidebar" :class="{ 'sidebar-open': mobileNavOpen }">
      <div class="sidebar-top">
        <div class="brand-lockup brand-lockup-light"><div class="brand-mark">BP</div><div class="brand-copy"><div class="brand-name">BluePrint <span>HR</span></div><div class="brand-caption">People operations</div></div></div>
        <button class="sidebar-close d-lg-none" aria-label="Close navigation" @click="mobileNavOpen = false"><i class="bi bi-x-lg"></i></button>
      </div>
      <div class="workspace-switcher"><div class="workspace-avatar">{{ (dashboard.tenant?.company_name || 'O')[0] }}</div><div class="min-w-0"><div class="workspace-label">Current workspace</div><div class="workspace-name text-truncate">{{ dashboard.tenant?.company_name || 'Your organization' }}</div></div><i class="bi bi-chevron-down ms-auto"></i></div>
      <div class="sidebar-label">Workspace</div>
      <nav class="sidebar-nav">
        <a v-for="item in navItems" :key="item.key" href="#" class="sidebar-link" :class="{ active: active === item.key }" @click.prevent="setActive(item.key)"><span class="sidebar-icon"><i class="bi" :class="item.icon"></i></span><span class="nav-label">{{ item.label }}</span><span v-if="item.key === 'leave' && dashboard.metrics.pending_leave" class="nav-count">{{ dashboard.metrics.pending_leave }}</span></a>
      </nav>
      <div class="sidebar-bottom">
        <div class="help-card"><div class="help-icon"><i class="bi bi-life-preserver"></i></div><div><strong>Need a hand?</strong><span>Visit the help center</span></div><i class="bi bi-arrow-up-right ms-auto"></i></div>
        <div class="sidebar-user"><div class="avatar avatar-sm">{{ initials }}</div><div class="min-w-0"><div class="sidebar-user-name text-truncate">{{ user.name }}</div><div class="sidebar-user-role text-truncate">{{ role }}</div></div><button class="icon-button icon-button-light ms-auto" title="Sign out" @click="signOut"><i class="bi bi-box-arrow-right"></i></button></div>
      </div>
    </aside>

    <main class="content-area">
      <header class="topbar">
        <div class="d-flex align-items-center gap-3 min-w-0"><button class="mobile-menu-button d-lg-none" aria-label="Open navigation" @click="mobileNavOpen = true"><i class="bi bi-list"></i></button><div class="breadcrumb-line"><span class="d-none d-sm-inline">Workspace</span><i class="bi bi-chevron-right d-none d-sm-inline"></i><strong>{{ pageMeta.label }}</strong></div></div>
        <div class="topbar-actions"><button class="icon-button" title="Refresh data" @click="loadAll"><i class="bi bi-arrow-clockwise" :class="{ 'spin': loading }"></i></button><div class="topbar-divider"></div><div class="topbar-user"><div class="avatar avatar-sm">{{ initials }}</div><div class="d-none d-md-block"><div class="topbar-user-name">{{ user.name }}</div><div class="topbar-user-role">{{ role }}</div></div><i class="bi bi-chevron-down d-none d-md-block text-muted"></i></div></div>
      </header>

      <div class="page-content">
        <div v-if="error" class="alert alert-danger alert-soft d-flex gap-2 align-items-start mb-4"><i class="bi bi-exclamation-circle"></i><span>{{ error }}</span><button class="btn-close ms-auto" aria-label="Dismiss" @click="error = ''"></button></div>
        <div v-if="loading" class="loading-bar"><span></span></div>

        <section v-if="active === 'dashboard'">
          <div class="page-heading dashboard-heading"><div><div class="eyebrow">{{ dashboard.tenant?.company_name || 'Your workspace' }}</div><h1>Good morning, {{ (user.name || 'there').split(' ')[0] }} <span class="heading-wave">✦</span></h1><p>Here’s what’s happening across your organization today.</p></div><div class="heading-actions"><span class="last-updated"><i class="bi bi-clock"></i> Updated just now</span><button v-if="canManagePeople" class="btn btn-primary" @click="setActive('employees')"><i class="bi bi-plus-lg me-2"></i>Add employee</button></div></div>
          <div class="metric-grid">
            <div class="metric-card metric-card-blue"><div class="metric-card-top"><span class="metric-label">Active headcount</span><span class="metric-icon"><i class="bi bi-people-fill"></i></span></div><div class="metric-value">{{ dashboard.metrics.headcount ?? 0 }}</div><div class="metric-foot"><span class="metric-positive"><i class="bi bi-arrow-up"></i> Workforce</span><span>Current total</span></div></div>
            <div class="metric-card metric-card-green"><div class="metric-card-top"><span class="metric-label">Monthly payroll</span><span class="metric-icon"><i class="bi bi-cash-stack"></i></span></div><div class="metric-value metric-money">{{ money(dashboard.metrics.monthly_payroll) }}</div><div class="metric-foot"><span class="metric-positive"><i class="bi bi-check2"></i> On track</span><span>Gross payroll</span></div></div>
            <div class="metric-card metric-card-orange"><div class="metric-card-top"><span class="metric-label">Branches</span><span class="metric-icon"><i class="bi bi-buildings-fill"></i></span></div><div class="metric-value">{{ dashboard.metrics.branches ?? 0 }}</div><div class="metric-foot"><span class="metric-neutral"><i class="bi bi-geo-alt"></i> Locations</span><span>Across your org</span></div></div>
            <div class="metric-card metric-card-purple"><div class="metric-card-top"><span class="metric-label">Pending leave</span><span class="metric-icon"><i class="bi bi-calendar-event-fill"></i></span></div><div class="metric-value">{{ dashboard.metrics.pending_leave ?? 0 }}</div><div class="metric-foot"><span class="metric-warning"><i class="bi bi-hourglass-split"></i> Needs review</span><span>Open requests</span></div></div>
          </div>
          <div class="dashboard-grid mt-4">
            <div class="panel-card recent-panel"><div class="panel-header"><div><h2>Recent employee records</h2><p>Latest additions to your active workforce</p></div><button class="text-button" @click="setActive('employees')">View directory <i class="bi bi-arrow-up-right"></i></button></div><div class="table-responsive"><table class="table workspace-table mb-0"><thead><tr><th>Employee</th><th>Department</th><th>Status</th><th class="text-end">Basic salary</th></tr></thead><tbody><tr v-for="employee in dashboard.employees" :key="employee.id"><td><div class="person-cell"><div class="avatar avatar-table">{{ fullName(employee).split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() }}</div><div><div class="person-name">{{ fullName(employee) }}</div><div class="person-meta">{{ employee.employee_no }}</div></div></div></td><td>{{ employee.department?.name || '—' }}</td><td><span class="status-pill" :class="statusClass(employee.employment_status)"><span></span>{{ employee.employment_status }}</span></td><td class="text-end amount-cell">{{ money(employee.basic_salary) }}</td></tr><tr v-if="!dashboard.employees.length"><td colspan="4" class="empty-state">No employee records yet.</td></tr></tbody></table></div></div>
            <div class="panel-card overview-panel"><div class="panel-header"><div><h2>Tenant overview</h2><p>Your organization details</p></div><span class="panel-more"><i class="bi bi-three-dots"></i></span></div><div class="tenant-identity"><div class="tenant-logo">{{ (dashboard.tenant?.company_name || 'O')[0] }}</div><div><div class="tenant-name">{{ dashboard.tenant?.company_name || 'Organization' }}</div><div class="tenant-type"><i class="bi bi-patch-check-fill"></i> Verified workspace</div></div></div><dl class="tenant-details"><div><dt>KRA PIN</dt><dd>{{ dashboard.tenant?.kra_pin || '—' }}</dd></div><div><dt>Email</dt><dd class="text-break">{{ dashboard.tenant?.email || '—' }}</dd></div><div><dt>Phone</dt><dd>{{ dashboard.tenant?.phone || '—' }}</dd></div><div><dt>Address</dt><dd>{{ dashboard.tenant?.address || '—' }}</dd></div></dl></div>
          </div>
        </section>

        <section v-else-if="active === 'employees'">
          <div class="page-heading"><div><div class="eyebrow">People directory</div><h1>Employees</h1><p>Manage profiles, statutory identifiers, salary and bank details.</p></div><div class="heading-actions"><button v-if="canManagePeople" class="btn btn-outline-primary" @click="downloadEmployees"><i class="bi bi-file-earmark-spreadsheet me-2"></i>Export</button><button v-if="canManagePeople" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#employeeModal"><i class="bi bi-plus-lg me-2"></i>Add employee</button></div></div>
          <div class="panel-card"><div class="panel-header directory-header"><div><h2>All employees</h2><p>{{ employees.total || employees.data?.length || 0 }} people in your directory</p></div><div class="search-placeholder"><i class="bi bi-search"></i><span>Search employees</span></div></div><div class="table-responsive"><table class="table workspace-table mb-0"><thead><tr><th>Employee</th><th>Contact</th><th>Department</th><th>Status</th><th class="text-end">Salary</th></tr></thead><tbody><tr v-for="employee in employees.data" :key="employee.id"><td><div class="person-cell"><div class="avatar avatar-table">{{ fullName(employee).split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase() }}</div><div><div class="person-name">{{ fullName(employee) }}</div><div class="person-meta">{{ employee.employee_no }}</div></div></div></td><td>{{ employee.email || employee.phone || '—' }}</td><td>{{ employee.department?.name || '—' }}</td><td><span class="status-pill" :class="statusClass(employee.employment_status)"><span></span>{{ employee.employment_status }}</span></td><td class="text-end amount-cell">{{ money(employee.basic_salary) }}</td></tr><tr v-if="!employees.data.length"><td colspan="5" class="empty-state">No employee records yet.</td></tr></tbody></table></div></div>
        </section>

        <section v-else-if="active === 'organization'"><div class="page-heading"><div><div class="eyebrow">Company structure</div><h1>Organization</h1><p>Branches and departments that bring your workforce together.</p></div></div><div class="row g-4"><div class="col-lg-6"><div class="panel-card h-100"><div class="panel-header"><div><h2>Branches</h2><p>{{ organization.branches.length }} locations</p></div><span class="section-icon section-icon-blue"><i class="bi bi-buildings"></i></span></div><ul class="clean-list"><li v-for="branch in organization.branches" :key="branch.id"><div class="list-leading"><span class="list-icon list-icon-blue"><i class="bi bi-geo-alt"></i></span><span><strong>{{ branch.name }}</strong><small>{{ branch.code || 'Branch location' }}</small></span></div><i class="bi bi-chevron-right list-arrow"></i></li><li v-if="!organization.branches.length" class="empty-list">No branches configured.</li></ul></div></div><div class="col-lg-6"><div class="panel-card h-100"><div class="panel-header"><div><h2>Departments</h2><p>{{ organization.departments.length }} teams</p></div><span class="section-icon section-icon-purple"><i class="bi bi-diagram-3"></i></span></div><ul class="clean-list"><li v-for="department in organization.departments" :key="department.id"><div class="list-leading"><span class="list-icon list-icon-purple"><i class="bi bi-people"></i></span><span><strong>{{ department.name }}</strong><small>{{ department.code || 'Organization team' }}</small></span></div><i class="bi bi-chevron-right list-arrow"></i></li><li v-if="!organization.departments.length" class="empty-list">No departments configured.</li></ul></div></div></div></section>

        <section v-else-if="active === 'leave'"><div class="page-heading"><div><div class="eyebrow">Time away</div><h1>Leave management</h1><p>Review requests, approvals and tenant-scoped leave balances.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#leaveModal"><i class="bi bi-calendar-plus me-2"></i>Request leave</button></div><div class="panel-card"><div class="panel-header"><div><h2>Leave requests</h2><p>Keep time-off decisions moving</p></div><span class="header-count">{{ leave.requests.length }} total</span></div><div class="table-responsive"><table class="table workspace-table mb-0"><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Days</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><tr v-for="request in leave.requests" :key="request.id"><td><div class="person-name">{{ fullName(request.employee) }}</div></td><td>{{ request.leave_type?.name }}</td><td>{{ request.start_date }} – {{ request.end_date }}</td><td>{{ request.days_requested }}</td><td><span class="status-pill" :class="statusClass(request.status)"><span></span>{{ request.status }}</span></td><td class="text-end"><template v-if="request.status === 'Pending' && canManagePeople"><button class="table-action table-action-success" title="Approve" @click="decideLeave(request, 'Approved')"><i class="bi bi-check-lg"></i></button><button class="table-action table-action-danger" title="Reject" @click="decideLeave(request, 'Rejected')"><i class="bi bi-x-lg"></i></button></template></td></tr><tr v-if="!leave.requests.length"><td colspan="6" class="empty-state">No leave requests.</td></tr></tbody></table></div></div></section>

        <section v-else-if="active === 'payroll'"><div class="page-heading"><div><div class="eyebrow">Compensation</div><h1>Payroll</h1><p>Configuration-driven PAYE, NSSF, SHIF and housing levy calculations.</p></div><select v-if="canProcessPayroll" class="form-select process-select" @change="processPayroll($event.target.value)"><option value="">Process a period…</option><option v-for="period in payroll.periods" :key="period.id" :value="period.id">{{ period.name }} ({{ period.status }})</option></select></div><div class="payroll-callout"><div class="callout-icon"><i class="bi bi-shield-check"></i></div><div><strong>Payroll is ready for review</strong><span>Rates are configuration-driven and every run is recorded in your audit trail.</span></div><i class="bi bi-arrow-right ms-auto"></i></div><div class="panel-card"><div class="panel-header"><div><h2>Payroll transactions</h2><p>Processed employee payments and deductions</p></div><span class="header-count">{{ payroll.transactions.length }} transactions</span></div><div class="table-responsive"><table class="table workspace-table mb-0"><thead><tr><th>Employee</th><th>Period</th><th>Gross</th><th>PAYE</th><th>NSSF</th><th>SHIF</th><th>Net pay</th><th></th></tr></thead><tbody><tr v-for="transaction in payroll.transactions" :key="transaction.id"><td><div class="person-name">{{ fullName(transaction.employee) }}</div></td><td>{{ transaction.period?.name }}</td><td>{{ money(transaction.gross_pay) }}</td><td>{{ money(transaction.paye) }}</td><td>{{ money(transaction.nssf) }}</td><td>{{ money(transaction.shif) }}</td><td class="amount-cell">{{ money(transaction.net_pay) }}</td><td><button class="table-action" title="Download payslip" @click="downloadPayslip(transaction.id)"><i class="bi bi-file-earmark-arrow-down"></i></button></td></tr><tr v-if="!payroll.transactions.length"><td colspan="8" class="empty-state">No payroll transactions. Process an open period to calculate payroll.</td></tr></tbody></table></div></div></section>

        <section v-else-if="active === 'ess'"><div class="page-heading"><div><div class="eyebrow">Your workspace</div><h1>My self-service</h1><p>Keep your profile and leave information close at hand.</p></div></div><div class="row g-4"><div class="col-lg-5"><div class="panel-card profile-card"><div class="profile-banner"></div><div class="profile-content"><div class="avatar avatar-profile">{{ initials }}</div><h2>{{ fullName(user.employee) || user.name }}</h2><p>{{ user.employee?.employee_no || user.email }}</p><span class="status-pill status-approved"><span></span> Active employee</span><dl class="profile-details"><div><dt>Department</dt><dd>{{ user.employee?.department?.name || '—' }}</dd></div><div><dt>Email</dt><dd class="text-break">{{ user.email }}</dd></div><div><dt>Phone</dt><dd>{{ user.employee?.phone || user.phone || '—' }}</dd></div></dl></div></div></div><div class="col-lg-7"><div class="panel-card h-100"><div class="panel-header"><div><h2>Leave balances</h2><p>Your available time away</p></div><span class="section-icon section-icon-green"><i class="bi bi-calendar2-heart"></i></span></div><div v-for="balance in leave.balances" :key="balance.id" class="balance-row"><div><strong>{{ balance.leave_type?.name }}</strong><small>Available balance</small></div><div class="balance-amount">{{ Number(balance.available_days).toFixed(2) }} <small>days</small></div></div><div v-if="!leave.balances.length" class="empty-state">No balances found.</div></div></div></div></section>

        <section v-else-if="active === 'audit'"><div class="page-heading"><div><div class="eyebrow">Trust and transparency</div><h1>Audit trail</h1><p>Immutable-style activity history for tenant operations.</p></div></div><div class="panel-card"><div class="panel-header"><div><h2>Recent activity</h2><p>Every important change, in one place</p></div></div><div class="table-responsive"><table class="table workspace-table mb-0"><thead><tr><th>When</th><th>User</th><th>Action</th><th>Entity</th><th>Details</th></tr></thead><tbody><tr v-for="log in dashboard.recent_audit" :key="log.id"><td>{{ log.created_at }}</td><td>{{ log.user?.name || 'System' }}</td><td><span class="status-pill status-neutral"><span></span>{{ log.action }}</span></td><td>{{ log.entity_type }} #{{ log.entity_id }}</td><td>{{ log.details || 'Record changed' }}</td></tr><tr v-if="!dashboard.recent_audit.length"><td colspan="5" class="empty-state">No recent activity.</td></tr></tbody></table></div></div></section>
      </div>
    </main>
  </div>

  <div class="modal fade" id="employeeModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content modal-modern"><form @submit.prevent="createEmployee"><div class="modal-header"><div><div class="eyebrow">People directory</div><h5 class="modal-title">Add a new employee</h5></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="form-section-label">Basic information</div><div class="row g-3"><div class="col-md-4"><label class="form-label">Employee No.</label><input v-model="employeeForm.employee_no" class="form-control" placeholder="e.g. BP-001" required></div><div class="col-md-4"><label class="form-label">First name</label><input v-model="employeeForm.first_name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Last name</label><input v-model="employeeForm.last_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input v-model="employeeForm.email" type="email" class="form-control"></div><div class="col-md-6"><label class="form-label">Phone</label><input v-model="employeeForm.phone" class="form-control"></div><div class="form-section-label mt-4">Employment details</div><div class="col-md-6"><label class="form-label">Basic salary (KES)</label><input v-model="employeeForm.basic_salary" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-6"><label class="form-label">Status</label><select v-model="employeeForm.employment_status" class="form-select"><option>Active</option><option>Inactive</option><option>On Leave</option></select></div><div class="col-md-6"><label class="form-label">Branch</label><select v-model="employeeForm.branch_id" class="form-select"><option :value="null">Select branch</option><option v-for="branch in organization.branches" :value="branch.id" :key="branch.id">{{ branch.name }}</option></select></div><div class="col-md-6"><label class="form-label">Department</label><select v-model="employeeForm.department_id" class="form-select"><option :value="null">Select department</option><option v-for="department in organization.departments" :value="department.id" :key="department.id">{{ department.name }}</option></select></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary"><i class="bi bi-check2 me-2"></i>Save employee</button></div></form></div></div></div>
  <div class="modal fade" id="leaveModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content modal-modern"><form @submit.prevent="submitLeave"><div class="modal-header"><div><div class="eyebrow">Time away</div><h5 class="modal-title">Request leave</h5></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div v-if="!isEmployee" class="mb-3"><label class="form-label">Employee ID</label><input v-model="leaveForm.employee_id" type="number" class="form-control"></div><div class="mb-3"><label class="form-label">Leave type</label><select v-model="leaveForm.leave_type_id" class="form-select" required><option :value="null">Select type</option><option v-for="type in leave.types" :key="type.id" :value="type.id">{{ type.name }}</option></select></div><div class="row g-3"><div class="col-6"><label class="form-label">Start date</label><input v-model="leaveForm.start_date" type="date" class="form-control" required></div><div class="col-6"><label class="form-label">End date</label><input v-model="leaveForm.end_date" type="date" class="form-control" required></div></div><div class="mt-3"><label class="form-label">Days requested</label><input v-model="leaveForm.days_requested" type="number" min="0.5" step="0.5" class="form-control" required></div><div class="mt-3"><label class="form-label">Reason <span class="text-muted fw-normal">(optional)</span></label><textarea v-model="leaveForm.reason" class="form-control" rows="3" placeholder="Add a note for your manager"></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary"><i class="bi bi-send me-2"></i>Submit request</button></div></form></div></div></div>
</template>
